version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    command: --max_allowed_packet=32505856
    container_name: mysql
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root9198
      MYSQL_DATABASE: atviras-seimas
      MYSQL_USER: dev
      MYSQL_PASSWORD: root9198
    ports:
      - 3306:3306
volumes:
  data:
