This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file ./magistrinis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file magistrinis.acn....done (38 entries accepted, 0 rejected).
Sorting entries....done (217 comparisons).
Generating output file magistrinis.acr....done (27 lines written, 0 warnings).
Output written in magistrinis.acr.
Transcript written in magistrinis.alg.
